name: "YouTube Audio to Drive (fixed)"

on:
  workflow_dispatch: {}
  # Nếu cần chạy định kỳ, mở comment dưới:
  # schedule:
  #   - cron: "0 */6 * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    permissions:
      contents: read

    env:
      # ==== TUỲ CHỈNH NHANH ====
      SLEEP_SECONDS: "8"
      MAX_PER_RUN: "40"

      # ==== GOOGLE DRIVE ====
      # Dùng 1 trong 2 (ưu tiên OAuth nếu cả hai có):
      GDRIVE_OAUTH_TOKEN_JSON: ${{ secrets.GDRIVE_OAUTH_TOKEN_JSON }}
      GDRIVE_SA_JSON: ${{ secrets.GDRIVE_SA_JSON }}
      GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}

      # ==== YouTube extractor (tuỳ chọn) ====
      PO_TOKEN: ${{ secrets.PO_TOKEN }}

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup Python"
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: "Install system deps (ffmpeg)"
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      # Cần nightly để tránh nsig/SABR
      - name: "Update yt-dlp to nightly"
        run: |
          python -m pip install --upgrade --pre yt-dlp-nightly
          yt-dlp --version

      - name: "Install Python deps"
        run: |
          python -m pip install --upgrade google-api-python-client google-auth google-auth-httplib2 google-auth-oauthlib

      # Ghi cookies_multi.txt nếu secret có set (đưa secrets vào env của step để YAML an toàn)
      - name: "Write cookies_multi.txt (optional)"
        env:
          _COOKIES: ${{ secrets.YT_COOKIES_MULTI }}
        run: |
          set -e
          mkdir -p data
          if [ -n "${_COOKIES}" ]; then
            printf '%s' "${_COOKIES}" > data/cookies_multi.txt
            echo "cookies_multi.txt created."
          else
            echo "YT_COOKIES_MULTI not set; skipping."
          fi

      # Ghi po_token.txt nếu muốn để ở file
      - name: "Write po_token.txt (optional)"
        env:
          _POFILE: ${{ secrets.PO_TOKEN_FILE }}
        run: |
          set -e
          mkdir -p data
          if [ -n "${_POFILE}" ]; then
            printf '%s' "${_POFILE}" > data/po_token.txt
            echo "po_token.txt created."
          else
            echo "PO_TOKEN_FILE not set; skipping."
          fi

      - name: "Run - YouTube audio to Drive"
        run: |
          python -u yt_audio_to_drive.py
